spring:
  application:
    name: web-node
server:
  port: 8080

grpc:
  client:
    authEnroll:
      address: ${AUTH_ENROLL_ADDRESS:static://auth-enrollment-service:9091}
      negotiationType: PLAINTEXT
    course:
      address: ${COURSE_ADDRESS:static://course-service:9092}
      negotiationType: PLAINTEXT
    grade:
      address: ${GRADE_ADDRESS:static://grade-service:9093}
      negotiationType: PLAINTEXT
